"""empty message

Revision ID: 69049db2b6f7
Revises: fe4156c52268
Create Date: 2021-03-06 02:02:43.665674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69049db2b6f7'
down_revision = 'fe4156c52268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_buy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=False),
    sa.Column('lprice', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('buy_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_buy')
    # ### end Alembic commands ###
