"""empty message

Revision ID: fcb89d66d0c7
Revises: e2ac4e9538ae
Create Date: 2021-03-06 12:25:35.144759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb89d66d0c7'
down_revision = 'e2ac4e9538ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_buy', schema=None) as batch_op:
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_buy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
